using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace AegisQuant.UI.Strategy.Models;

/// <summary>
/// Represents a strategy that is managed by the multi-strategy manager.
/// Includes enable/disable state and runtime statistics.
/// </summary>
public class ManagedStrategy : INotifyPropertyChanged, IDisposable
{
    private bool _isEnabled = true;
    private bool _isRunning;
    private int _signalCount;
    private int _tradeCount;
    private double _pnl;
    private string _lastError = string.Empty;
    private DateTime? _lastSignalTime;

    /// <summary>
    /// Unique identifier for this managed strategy instance.
    /// </summary>
    public string Id { get; }

    /// <summary>
    /// The underlying strategy implementation.
    /// </summary>
    public IStrategy Strategy { get; }

    /// <summary>
    /// Strategy information and metadata.
    /// </summary>
    public StrategyInfo Info { get; }

    /// <summary>
    /// Gets or sets whether this strategy is enabled for signal generation.
    /// </summary>
    public bool IsEnabled
    {
        get => _isEnabled;
        set => SetField(ref _isEnabled, value);
    }

    /// <summary>
    /// Gets or sets whether this strategy is currently running.
    /// </summary>
    public bool IsRunning
    {
        get => _isRunning;
        set => SetField(ref _isRunning, value);
    }

    /// <summary>
    /// Number of signals generated by this strategy.
    /// </summary>
    public int SignalCount
    {
        get => _signalCount;
        set => SetField(ref _signalCount, value);
    }

    /// <summary>
    /// Number of trades executed from this strategy's signals.
    /// </summary>
    public int TradeCount
    {
        get => _tradeCount;
        set => SetField(ref _tradeCount, value);
    }

    /// <summary>
    /// Profit and loss for this strategy.
    /// </summary>
    public double PnL
    {
        get => _pnl;
        set => SetField(ref _pnl, value);
    }

    /// <summary>
    /// Last error message if any.
    /// </summary>
    public string LastError
    {
        get => _lastError;
        set => SetField(ref _lastError, value);
    }

    /// <summary>
    /// Time of the last signal generated.
    /// </summary>
    public DateTime? LastSignalTime
    {
        get => _lastSignalTime;
        set => SetField(ref _lastSignalTime, value);
    }

    /// <summary>
    /// Display name combining strategy name and type.
    /// </summary>
    public string DisplayName => $"{Strategy.Name} ({Strategy.Type})";

    public ManagedStrategy(IStrategy strategy, StrategyInfo info)
    {
        Id = Guid.NewGuid().ToString("N")[..8];
        Strategy = strategy ?? throw new ArgumentNullException(nameof(strategy));
        Info = info ?? throw new ArgumentNullException(nameof(info));
    }

    /// <summary>
    /// Process a tick and return the signal if enabled.
    /// </summary>
    public Signal ProcessTick(StrategyContext context)
    {
        if (!IsEnabled || !IsRunning)
            return Signal.None;

        try
        {
            var signal = Strategy.OnTick(context);
            if (signal != Signal.None)
            {
                SignalCount++;
                LastSignalTime = DateTime.Now;
            }
            LastError = string.Empty;
            return signal;
        }
        catch (Exception ex)
        {
            LastError = ex.Message;
            return Signal.None;
        }
    }

    /// <summary>
    /// Reset runtime statistics.
    /// </summary>
    public void ResetStats()
    {
        SignalCount = 0;
        TradeCount = 0;
        PnL = 0;
        LastError = string.Empty;
        LastSignalTime = null;
    }

    public void Dispose()
    {
        Strategy.Dispose();
    }

    #region INotifyPropertyChanged

    public event PropertyChangedEventHandler? PropertyChanged;

    protected virtual void OnPropertyChanged([CallerMemberName] string? propertyName = null)
    {
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }

    protected bool SetField<T>(ref T field, T value, [CallerMemberName] string? propertyName = null)
    {
        if (EqualityComparer<T>.Default.Equals(field, value)) return false;
        field = value;
        OnPropertyChanged(propertyName);
        return true;
    }

    #endregion
}
