using System;
using System.Collections.Generic;
using AegisQuant.UI.Strategy.Models;

namespace AegisQuant.UI.Strategy;

/// <summary>
/// Trading signal generated by a strategy.
/// </summary>
public enum Signal
{
    /// <summary>No action</summary>
    None = 0,
    /// <summary>Buy signal</summary>
    Buy = 1,
    /// <summary>Sell signal</summary>
    Sell = -1
}

/// <summary>
/// Type of strategy implementation.
/// </summary>
public enum StrategyType
{
    /// <summary>Built-in Rust strategy via FFI</summary>
    BuiltIn,
    /// <summary>JSON/YAML configuration-based strategy</summary>
    JsonConfig,
    /// <summary>Python script strategy</summary>
    PythonScript
}

/// <summary>
/// Interface for all trading strategies.
/// Supports built-in, JSON config, and Python script strategies.
/// </summary>
public interface IStrategy : IDisposable
{
    /// <summary>
    /// Gets the strategy name.
    /// </summary>
    string Name { get; }

    /// <summary>
    /// Gets the strategy description.
    /// </summary>
    string Description { get; }

    /// <summary>
    /// Gets the strategy type.
    /// </summary>
    StrategyType Type { get; }

    /// <summary>
    /// Gets the strategy parameters.
    /// </summary>
    IReadOnlyDictionary<string, object> Parameters { get; }

    /// <summary>
    /// Process a tick and generate a trading signal.
    /// </summary>
    /// <param name="context">Strategy execution context</param>
    /// <returns>Trading signal (Buy, Sell, or None)</returns>
    Signal OnTick(StrategyContext context);

    /// <summary>
    /// Reset the strategy state.
    /// </summary>
    void Reset();

    /// <summary>
    /// Validate the strategy configuration.
    /// </summary>
    /// <returns>Validation result with any errors</returns>
    ValidationResult Validate();
}
